### ISSUE TITLE
Replace the test loading system

### ISSUE THREAD

**Issue by kilahm** [HackPack/HackUnit#26]
The current loading system uses an outdated Hack parsing library and reflection to locate test cases.  The library currently in use (https://github.com/HackPack/HackClassScanner) is based on an early version of a library written by Fred Emmott: https://github.com/fredemmott/definitions-finder

I think it would be nice to use Fred's library directly rather than my cheap copy.

@belka-ew do you think you could look into this?  It will require a pretty heavy refactor of `src/Test/Loader.php` with a possible creation of a new `Scanner` class to wrap the recursive path searching logic.

**Comment by belka-ew** [comment]
thanks for your response. Sure. I looked today a bit deeper into the definitions loader and the HackUnit code and I think that I'll just create a fork from the HackUnit repo and will make pull requests for the first time so you can review it before submitting since I don't know the codebase very well yet.
